language: objective-c
osx_image: xcode7.3
script:
  - xcodebuild -project NumPad.xcodeproj -scheme Example test -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6s,OS=9.3' build test
after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'Example'
